# Generated by Django 4.1.7 on 2023-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('ubicacion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('fechaFundacion', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('paginaWeb', models.CharField(max_length=500)),
            ],
        ),
    ]
